version: "2.1"

services:
  # ------------------------------------------------------------------------------------
  # FlowFuse Device Agent
  # ------------------------------------------------------------------------------------
  devagent:
    build:
      context: ./device-agent
    restart: always
    network_mode: host
    privileged: true
    ports:
      - "1880:1880"
    volumes:
      - ff-device:/opt/flowfuse-device
  
  # ------------------------------------------------------------------------------------
  # Influxdb
  # ------------------------------------------------------------------------------------
  influxdb:
    image: influxdb:1.7.11
    restart: unless-stopped
    ports:
        - '8086'
    volumes:
        - influxdb-data:/var/lib/influxdb
        - influxdb-etc:/etc/influxdb



volumes:
  ff-device:
  influxdb-data:
  influxdb-etc:
